name: Build document to artifact
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latex
        run: sudo apt-get update && sudo apt-get install -y texlive-full
      - name: Build document
        run: pdflatex -interaction=nonstopmode main.tex && ls .
      

      - name: Archive pdf artifacts
        uses: actions/upload-artifact@v1
        with:
          name: main.pdf
          path: ./main.pdf