name: Spell Checking
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Spell checking
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download textidot
        run: wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.1/textidote.jar
      - name: Run textidot
        run: now=$(date +"%m_%d_%Y") && mkdir -p spell && java -jar textidote.jar --check en --dict dico.txt --output json main.tex > report.json || true
      - name: Run textidot
        run: now=$(date +"%m_%d_%Y") && mkdir -p spell && java -jar textidote.jar --check en --dict dico.txt --output html main.tex > report.html || true
      - name: Create pdf
        run: sudo apt-get update && sudo apt-get install chromium-browser -y && chromium-browser  --headless --disable-gpu --print-to-pdf=report.pdf report.html
      - name: Create issue content
        run: python3 .github/parse_json2md.py report.json main.tex $(git log -n 1 --pretty=%H) $(git config --get remote.origin.url) > report.md

      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"
        
      - name: GIT
        run: git rm -rf . && git checkout -b reports && git add report.json report.pdf && git commit -m 'Spell check report' 
        
      - name: GIT
        run: git push origin reports --force

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Spell checking result
          content-filepath: report.md
          labels: report, automated issue
          project: CROW-paper
          project-column: SPELL_CHECK
        if: always()
